ALTER TABLE sales_schema.prescription_items 
ALTER COLUMN dosage_per_day TYPE DECIMAL(10,2),
ALTER COLUMN morning DROP DEFAULT,
ALTER COLUMN morning TYPE DECIMAL(10,2) USING (CASE WHEN morning THEN 1.0 ELSE 0.0 END),
ALTER COLUMN morning SET DEFAULT 0,
ALTER COLUMN noon DROP DEFAULT,
ALTER COLUMN noon TYPE DECIMAL(10,2) USING (CASE WHEN noon THEN 1.0 ELSE 0.0 END),
ALTER COLUMN noon SET DEFAULT 0,
ALTER COLUMN night DROP DEFAULT,
ALTER COLUMN night TYPE DECIMAL(10,2) USING (CASE WHEN night THEN 1.0 ELSE 0.0 END),
ALTER COLUMN night SET DEFAULT 0;
